version: '3.5'
services:
  zevrant-keycloak-service-db:
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}" ]
      timeout: 45s
      interval: 10s
      retries: 10
    ports:
      - "5441:5432"
    image: postgres:latest
    volumes:
      - /home/zevrant/keycloak/postgres:/opt/postgres
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: example
      POSTGRES_DB: keycloak
      PGDATA: /opt/postgres/
  zevrant-keycloak-service:
    depends_on:
      - zevrant-keycloak-service-db
    ports:
      - "9011:8443"
    image: docker.io/zevrant/keycloak-service:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_ADDR: 192.168.1.21
      DB_PORT: 5441
      DB_DATABASE: keycloak
      DB_USER: sa
      DB_PASSWORD: example
      DB_VENDOR: POSTGRES
      SERVICE_NAME: localhost
      POD_IP: 127.0.0.1
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
