apiVersion: v1
kind: Service
metadata:
  name: zevrant-foundry-service-prima
  namespace: zevrant-home-services-prod
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 30000
      nodePort: 30122
  selector:
    app: zevrant-foundry-service-prima


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zevrant-foundry-service-prima
  labels:
    app: zevrant-foundry-service-prima
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zevrant-foundry-service-prima
  template:
    metadata:
      labels:
        app: zevrant-foundry-service-prima
    spec:
      volumes:
        - name: foundry-data
          nfs:
            server: 192.168.0.127
            path: /i-data/420aa917/nfs/prima-foundry
      containers:
        - name: zevrant-foundry-service-prima
          image: zevrant/zevrant-foundry-service:latest
          ports:
            - containerPort: 30000
          volumeMounts:
            - name: foundry-data
              mountPath: /root/.local/share/FoundryVTT/