apiVersion: v1
kind: Service
metadata:
  name: ingress-splunk-nodeport-prod
  namespace: zevrant-home-services-prod
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30130
  selector:
    app: splunk-operator