apiVersion: v1
kind: Service
metadata:
  name: ingress-nodeport-prod
  namespace: zevrant-home-services-prod
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30123
  selector:
    app: zevrant-home-ui
#
#---
#
#apiVersion: v1
#kind: Service
#metadata:
#  name: ingress-nodeport-prod
#  namespace: zevrant-home-services-prod
#spec:
#  type: NodePort
#  ports:
#    - port: 9090
#      targetPort: 9090
#      nodePort: 30122
#  selector:
#    app: zevrant-prometheus-service
