stages:
  - deployGitlab
  - deployIngressShared

Deploy Gitlab:
  stage: deployGitlab
  script:
    - kubectl apply -f kubernetes/gitlab-service.yml --namespace=shared

Deploy Ingress:
  stage: deployIngressShared
  script:
    - kubectl apply -f kubernetes/nginx-ingress-shared.yml --namespace=shared