apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: createDeployments
rules:
  - apiGroups:
      - "apps" # "" indicates the core API group
    resources:
      - "deployments"
    verbs:
      - "create"