apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: createServices
rules:
  - apiGroups:
      - "" # "" indicates the core API group
    resources:
      - "services"
    verbs:
      - "create"