apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: readOnly
rules:
  - apiGroups: [ "", "apps" ] # "" indicates the core API group
    resources: [ "pods", "services", "deployments" ]
    verbs: [ "get", "watch", "list" ]
