apiVersion: v1
kind: Service
metadata:
  name: zevrant-acrarium-service
  namespace: zevrant-home-services-develop
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30131
  selector:
    app: zevrant-acrarium-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zevrant-acrarium-service-deployment
  namespace: zevrant-home-services-develop
  labels:
    app: zevrant-acrarium-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zevrant-acrarium-service
  template:
    metadata:
      labels:
        app: zevrant-acrarium-service
    spec:
      volumes:
        - name: acrarium-db
          nfs:
            server: 192.168.1.11
            path: /acrarium-dev
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        architecture: amd64
      containers:
        - name: mysql
          volumeMounts:
            - name: acrarium-db
              mountPath: /var/lib/mysql
          image: mysql:5.7
          env:
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: 'true'
            - name: MYSQL_DATABASE
              value: acrarium
            - name: MYSQL_USER
              value: sa
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: acrarium-db-password
                  key: password
          ports:
            - containerPort: 3306
        - name: acrarium
          image: f43nd1r/acrarium:1.5.0
          env:
            - name: SPRING_DATASOURCE_URL
              value: 'jdbc:mysql://localhost:3306/acrarium?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC'
            - name: SPRING_DATASOURCE_USERNAME
              value: sa
            #            - name: SPRING_MAIL_HOST
            #              value: 'smtp.gmail.com'
            #            - name: SPRING_MAIL_PORT
            #              value: '587'
            #            - name: SPRING_MAIL_SMTP_AUTH
            #              value: 'true'
            #            - name: SPRING_MAIL_SMTP_STARTTLS_ENABLE
            #              value: 'true'
            #            - name: SPRING_MAIL_SMTP_STARTTLS_REQUIRED
            #              value: 'true'
            #            - name: SPRING_MAIL_USERNAME
            #              valueFrom:
            #                secretKeyRef:
            #                  name: smtp-user
            #                  key: password
            #            - name: SPRING_MAIL_PASSWORD
            #              valueFrom:
            #                secretKeyRef:
            #                  name: smtp-password
            #                  key: password
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: acrarium-db-password
                  key: password
          #                  TODO: I don't like having to use kubernetes env vars for secrets
          ports:
            - containerPort: 8080