apiVersion: v1
kind: Service
metadata:
  name: ingress-grafana-nodeport-dev
  namespace: zevrant-home-services-develop
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30128
  selector:
    app: zevrant-prometheus-service

---

apiVersion: v1
kind: Service
metadata:
  name: ingress-prometheus-nodeport-dev
  namespace: zevrant-home-services-develop
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30126
  selector:
    app: zevrant-prometheus-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zevrant-prometheus-service-deployment
  labels:
    app: zevrant-prometheus-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zevrant-prometheus-service
  template:
    metadata:
      labels:
        app: zevrant-prometheus-service
    spec:
      nodeSelector:
        architecture: amd64
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: database
          nfs:
            server: 192.168.1.11
            path: /grafana-dev
        - name: certs
          nfs:
            server: 192.168.1.11
            path: /grafana-dev-certs
      containers:
        - name: grafana
          image: zevrant/grafana:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: database
              mountPath: /var/lib/grafana
            - name: certs
              mountPath: /etc/ssl/certs/
        - name: zevrant-prometheus-service
          image: zevrant/prometheus:2.27.1
          ports:
            - containerPort: 3310