apiVersion: v1
kind: Service
metadata:
  name: ingress-nodeport-develop
  namespace: zevrant-home-services-develop
spec:
  type: NodePort
  ports:
    - port: 2222
      targetPort: 2222
      nodePort: 30124
  selector:
    app: zevrant-openssh-server
