apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
automountServiceAccountToken: false
imagePullSecrets:
  - name: regcred
---

apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: jenkins-read-only
  namespace: jenkins
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: readOnly # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: jenkins-read-only
  namespace: zevrant-home-services-develop
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: readOnly # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-create-pods
  namespace: jenkins
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: createPods # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-create-services-zevrant-home-services-develop
  namespace: zevrant-home-services-develop
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: createServices # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-create-services-zevrant-home-services-prod
  namespace: zevrant-home-services-develop
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: createServices # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-create-deployments-zevrant-home-services-develop
  namespace: zevrant-home-services-develop
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: createDeployments # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-create-deployments-zevrant-home-services-develop
  namespace: zevrant-home-services-prod
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: createDeployments # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io