apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
spec:
  ports:
    - port: 443

---

apiVersion: v1
kind: Endpoint
metadata:
  name: gitlab-service
subsets:
  - addresses:
      - ip: 192.168.0.73
      ports:
        - port: 7443