apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-point
spec:
  rules:
    - host: gitlab.zevrant-services.com
      http:
        paths:
          - path: /
            backend:
              serviceName: gitlab
              servicePort: 443
