#apiVersion: rbac.authorization.k8s.io/v1
#kind: Role
#metadata:
#  namespace: default
#  name: jenkins
#rules:
#  - apiGroups: [""] # "" indicates the core API group
#    resources: ["pods"]
#    verbs: ["get", "watch", "list"]

#---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
automountServiceAccountToken: false